# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASIGNA_EMPRESA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDEMPRESA', models.IntegerField(null=True)),
                ('IDALUMNO', models.IntegerField(null=True)),
                ('FECHA_VINCU', models.DateField()),
                ('FECHA_CAMBIO', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ID_ASIGNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idasigna', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='asigna_empresa',
            name='IDASIGNA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.ID_ASIGNA'),
        ),
    ]
