# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATALUMNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATRICULA', models.IntegerField()),
                ('IDPROCESO', models.IntegerField(null=True)),
                ('IDCARRERA', models.IntegerField(null=True)),
                ('IDEMPRESA', models.IntegerField(null=True)),
                ('ACTIVO', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ID_ALUMNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idalumno', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='catalumno',
            name='IDALUMNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.ID_ALUMNO'),
        ),
    ]
