# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-27 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0002_auto_20160727_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATCALIFICACIONES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDALUMNO', models.IntegerField()),
                ('CAL_AA', models.IntegerField()),
                ('CAL_AL', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CATCARRERAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(max_length=50)),
                ('ABREVIATURA', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CATEMPRESAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
                ('REPRESENTANTE', models.CharField(max_length=100, null=True)),
                ('TELEFONO', models.BigIntegerField()),
                ('DOMICILIO', models.CharField(max_length=120)),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ID_CALIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcalif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ID_CARRERA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcarrera', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ID_EMPRESA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='catempresas',
            name='IDEMPRESA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.ID_EMPRESA'),
        ),
        migrations.AddField(
            model_name='catcarreras',
            name='IDCARREA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.ID_CARRERA'),
        ),
        migrations.AddField(
            model_name='catcalificaciones',
            name='IDCALIF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.ID_CALIF'),
        ),
    ]
