# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0004_auto_20160727_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID_ASIGNA',
        ),
        migrations.RemoveField(
            model_name='catalumno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catcalificaciones',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catcarreras',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catempresas',
            name='id',
        ),
        migrations.AlterField(
            model_name='catalumno',
            name='IDALUMNO',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catcalificaciones',
            name='IDCALIF',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catcarreras',
            name='IDCARREA',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catempresas',
            name='IDEMPRESA',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ID_ALUMNO',
        ),
        migrations.DeleteModel(
            name='ID_CALIF',
        ),
        migrations.DeleteModel(
            name='ID_CARRERA',
        ),
        migrations.DeleteModel(
            name='ID_EMPRESA',
        ),
    ]
