# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-29 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0006_cathistrep_catmaestros_catpersonas_periodoescolar_proceso_tipopersona_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USUARIOS',
        ),
        migrations.RemoveField(
            model_name='catpersonas',
            name='FECHA_NAC',
        ),
        migrations.AlterField(
            model_name='asigna_empresa',
            name='IDALUMNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATALUMNO'),
        ),
        migrations.AlterField(
            model_name='asigna_empresa',
            name='IDEMPRESA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATEMPRESAS'),
        ),
    ]
