# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0007_auto_20160729_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATALUMNOS',
            fields=[
                ('IDALUMNO', models.AutoField(primary_key=True, serialize=False)),
                ('MATRICULA', models.IntegerField()),
                ('ACTIVO', models.BooleanField()),
                ('IDCARRERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATCARRERAS')),
                ('IDEMPRESA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATEMPRESAS')),
            ],
        ),
        migrations.CreateModel(
            name='ESTATUS',
            fields=[
                ('IDESTATUS', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CATHISTREP',
        ),
        migrations.AddField(
            model_name='catpersonas',
            name='PASSWORD',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='catpersonas',
            name='USUARIO',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='asigna_empresa',
            name='IDALUMNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATALUMNOS'),
        ),
        migrations.AlterField(
            model_name='catcalificaciones',
            name='IDALUMNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATALUMNOS'),
        ),
        migrations.AlterField(
            model_name='catmaestros',
            name='IDPERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATPERSONAS'),
        ),
        migrations.AlterField(
            model_name='catpersonas',
            name='IDTIPOPERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.TIPOPERSONA'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='ID_PERIODO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.PERIODOESCOLAR'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='NOMBRE',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='CATALUMNO',
        ),
        migrations.AddField(
            model_name='catalumnos',
            name='IDESTATUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.ESTATUS'),
        ),
        migrations.AddField(
            model_name='catalumnos',
            name='IDPROCESO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.PROCESO'),
        ),
    ]
