# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0008_auto_20160730_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATHISTREP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_SUBIDA', models.DateField()),
                ('TIPO_REP', models.CharField(max_length=20)),
                ('IDALUMNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwedeeapp.CATALUMNOS')),
            ],
        ),
    ]
