# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0009_cathistrep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catpersonas',
            name='PASSWORD',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='catpersonas',
            name='USUARIO',
            field=models.CharField(max_length=30),
        ),
    ]
