# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0010_auto_20160730_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalumnos',
            name='MATRICULA',
            field=models.CharField(max_length=6),
        ),
    ]
