# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-04 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0011_auto_20160731_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catcarreras',
            old_name='IDCARREA',
            new_name='IDCARRERA',
        ),
        migrations.AlterField(
            model_name='catalumnos',
            name='IDALUMNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siwedeeapp.CATPERSONAS'),
        ),
    ]
