# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0012_auto_20160804_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalumnos',
            name='IDALUMNO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siwedeeapp.CATPERSONAS'),
        ),
    ]
