# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-04 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwedeeapp', '0014_remove_catpersonas_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catpersonas',
            name='SEXO',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
